### ISSUE TITLE
Numbers in glosses

### ISSUE THREAD

**Issue by MiinaNo** [cldf-datasets/uratyp#19]
@xrotwang just for us to rembember. I checked the examples in the database. There is still the problem with the numbers in glosses. Maybe you did not manage to deal with this yet? For instance, [Sentence 59:](https://uralic.clld.org/sentences/59) looks like this:

sese tulob tulo-b
se-se
this-DEF come-SG

this comes

But it should be 3SG. The same way, for instance, 'you' is only SG not 2SG etc. This is a general problem in all language tables.

**Comment by xrotwang** [comment]
That problem is solved (https://github.com/clld/clld/commit/b131d2d0b40d531ef2c6665594e061c08de5821d) - but not yet deployed on the server.

**Comment by xrotwang** [comment]
Also, I'm not sure when I updated the data on the server last. So the most recent work I did on examples is here: https://github.com/cldf-datasets/uratyp/pull/18/files

**Comment by MiinaNo** [comment]
Aaa.. ok, great!

**Comment by MiinaNo** [comment]
Actually, one other comment about the examples. Would it be possible to retaine the square brackets in the phonology examples, i.e. in all the examples between UT116-UT166 if a square bracket is used it is retained. Thus, **instead of****
_väsymys
ˈvæ.sy.mys_
'tiredness'
**it would be** 
_väsymys_
[ˈvæ.sy.mys]
'tiredness'
This would imply that we are dealing with IPA; the text should not be in italics.

[]-s are also used in the questions UT001-UT115 in the case of languages that use **cyrillic** (e.g. Komi), however, in these lines it is fine to omit them. And maybe it is even the only option because in the case of IPA we would run into problem that we have the transliteration in brackets as well as IPA.

**Comment by xrotwang** [comment]
will look into this on Monday
