### ISSUE TITLE
zenodo snapshot for this repository

### ISSUE THREAD

**Issue by JakeJing** [cldf-datasets/uratyp#5]
@xrotwang Outi & Michael are suggesting that we can make a zenodo snapshot of the current repos. so that there is a doi for cross-reference. Can you pls do it, since I may not have access to it? Thanks!

**Comment by chrzyki** [comment]
@JakeJing let me know if I can help with anything else! Here are the DOIs:

- https://doi.org/10.5281/zenodo.5236366 (this points to the v0.1 release)
- https://doi.org/10.5281/zenodo.5236365 (this is the version-independent DOI that will always point to the latest release)

**Comment by JakeJing** [comment]
@chrzyki It looks good. Many thanks!
